2025-01-15 21:30:42,403 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:30:42,403 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:30:43,339 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:30:43,339 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-15 21:30:43,339 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-15 21:30:43,339 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-15 21:30:43,339 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-15 21:30:43,340 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-15 21:31:38,756 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:31:38,757 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:31:38,932 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:31:38,932 - process_location.py - Line: 26 - ERROR - !! Failed to load configuration: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:31:38,932 - main_etl_runner.py - Line: 40 - ERROR - Error during ETL Runner initialization: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:31:38,933 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:31:49,169 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:31:49,169 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:31:49,336 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:31:49,336 - process_location.py - Line: 26 - ERROR - !! Failed to load configuration: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:31:49,337 - main_etl_runner.py - Line: 40 - ERROR - Error during ETL Runner initialization: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:31:49,337 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:32:47,092 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:32:47,093 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:32:47,268 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:32:47,268 - process_location.py - Line: 26 - ERROR - !! Failed to load configuration: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:32:47,269 - main_etl_runner.py - Line: 40 - ERROR - Error during ETL Runner initialization: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:32:47,269 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: [Errno 2] No such file or directory: 'config/location_config.json'
2025-01-15 21:34:50,851 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:34:50,851 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:34:51,036 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:34:51,037 - process_location.py - Line: 24 - INFO - Configuration for location table loaded successfully
2025-01-15 21:34:51,037 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-15 21:34:51,037 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-15 21:34:51,037 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-15 21:34:51,038 - process_location.py - Line: 31 - INFO - - Starting the data processing for location table...
2025-01-15 21:34:51,038 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Madrid, Spain
2025-01-15 21:34:51,039 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Barcelona, Spain
2025-01-15 21:34:51,055 - process_location.py - Line: 102 - INFO - Data successfully written to output/location_2024-10-07.csv !
2025-01-15 21:34:51,055 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-15 21:34:51,055 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-15 21:41:07,881 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:41:07,881 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:41:08,068 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:41:08,068 - process_location.py - Line: 24 - INFO - Configuration for location table loaded successfully
2025-01-15 21:41:08,068 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-15 21:41:08,069 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-15 21:41:08,069 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-15 21:41:08,069 - process_location.py - Line: 31 - INFO - - Starting the data processing for location table...
2025-01-15 21:41:08,070 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Madrid, Spain
2025-01-15 21:41:08,070 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Barcelona, Spain
2025-01-15 21:41:08,070 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Lisbon, Portugal
2025-01-15 21:41:08,070 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Paris, France
2025-01-15 21:41:08,072 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Rome, Italy
2025-01-15 21:41:08,072 - process_location.py - Line: 86 - INFO - Successfully processed data for city: Amsterdam, Netherlands
2025-01-15 21:41:08,083 - process_location.py - Line: 102 - INFO - Data successfully written to output/location_2024-10-07.csv !
2025-01-15 21:41:08,083 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-15 21:41:08,083 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-15 21:41:54,079 - utils.py - Line: 148 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-01-15 21:41:54,079 - utils.py - Line: 160 - INFO - NumExpr defaulting to 8 threads.
2025-01-15 21:41:54,264 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:41:54,265 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-15 21:41:54,265 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-15 21:41:54,265 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-15 21:41:54,265 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-15 21:41:54,266 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-15 21:41:54,266 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Madrid, Spain
2025-01-15 21:41:54,267 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Barcelona, Spain
2025-01-15 21:41:54,267 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Lisbon, Portugal
2025-01-15 21:41:54,267 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Paris, France
2025-01-15 21:41:54,267 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Rome, Italy
2025-01-15 21:41:54,267 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Amsterdam, Netherlands
2025-01-15 21:41:54,273 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-15 21:41:54,273 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-15 21:41:54,273 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-15 21:44:15,812 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-15 21:44:15,813 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-15 21:44:15,813 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-15 21:44:15,814 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-15 21:44:15,814 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-15 21:44:15,814 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-15 21:44:15,815 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Jakarta, Indonesia
2025-01-15 21:44:15,815 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bandung, Indonesia
2025-01-15 21:44:15,816 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Surabaya, Indonesia
2025-01-15 21:44:15,816 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Yogyakarta, Indonesia
2025-01-15 21:44:15,816 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Medan, Indonesia
2025-01-15 21:44:15,823 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-15 21:44:15,824 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-15 21:44:15,824 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 14:32:49,800 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:32:49,804 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:32:49,804 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:32:49,804 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:32:49,804 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 14:32:49,809 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 14:32:49,810 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Jakarta, Indonesia
2025-01-16 14:32:49,810 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bandung, Indonesia
2025-01-16 14:32:49,810 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Surabaya, Indonesia
2025-01-16 14:32:49,810 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Yogyakarta, Indonesia
2025-01-16 14:32:49,810 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Medan, Indonesia
2025-01-16 14:32:49,821 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-16 14:32:49,821 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 14:32:49,822 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 14:34:15,606 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:34:15,609 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:34:15,614 - process_current.py - Line: 24 - INFO - Configuration for current table loaded successfully
2025-01-16 14:34:15,616 - process_forecast.py - Line: 24 - INFO - Configuration for forecast table loaded successfully
2025-01-16 14:34:15,616 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:34:15,618 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:34:15,618 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 14:34:15,621 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 14:34:15,623 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Jakarta, Indonesia
2025-01-16 14:34:15,623 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bandung, Indonesia
2025-01-16 14:34:15,624 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Surabaya, Indonesia
2025-01-16 14:34:15,624 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Yogyakarta, Indonesia
2025-01-16 14:34:15,625 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Medan, Indonesia
2025-01-16 14:34:15,631 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-16 14:34:15,631 - process_current.py - Line: 31 - INFO - - Starting the data processing for current table...
2025-01-16 14:34:15,632 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Jakarta, Indonesia
2025-01-16 14:34:15,632 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Bandung, Indonesia
2025-01-16 14:34:15,633 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Surabaya, Indonesia
2025-01-16 14:34:15,633 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Yogyakarta, Indonesia
2025-01-16 14:34:15,633 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Medan, Indonesia
2025-01-16 14:34:15,656 - process_current.py - Line: 103 - INFO - Data successfully written to output/current_2024-10-07.csv
2025-01-16 14:34:15,656 - process_forecast.py - Line: 31 - INFO - - Starting the data processing for forecast table...
2025-01-16 14:34:15,656 - process_forecast.py - Line: 116 - ERROR - !! Error writing data to CSV: list index out of range
2025-01-16 14:34:15,657 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: list index out of range
2025-01-16 14:34:15,657 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: list index out of range
2025-01-16 14:37:38,472 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:37:38,478 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:37:38,482 - process_current.py - Line: 24 - INFO - Configuration for current table loaded successfully
2025-01-16 14:37:38,489 - process_forecast.py - Line: 24 - INFO - Configuration for forecast table loaded successfully
2025-01-16 14:37:38,489 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:37:38,489 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:37:38,489 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 14:37:38,490 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 14:37:38,491 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:37:38,492 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:37:38,492 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:37:38,492 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:37:38,492 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:37:38,502 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-16 14:37:38,502 - process_current.py - Line: 31 - INFO - - Starting the data processing for current table...
2025-01-16 14:37:38,502 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:37:38,508 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:37:38,508 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:37:38,508 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:37:38,508 - process_current.py - Line: 84 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:37:38,509 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:37:38,509 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:37:38,509 - process_current.py - Line: 84 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:37:38,509 - process_current.py - Line: 87 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:37:38,533 - process_current.py - Line: 103 - INFO - Data successfully written to output/current_2024-10-07.csv
2025-01-16 14:37:38,533 - process_forecast.py - Line: 31 - INFO - - Starting the data processing for forecast table...
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-07
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-08
2025-01-16 14:37:38,533 - etl_helpers.py - Line: 113 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-09
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-07
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-08
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-09
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-07
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-08
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-09
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-07
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-08
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-09
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-07
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-08
2025-01-16 14:37:38,533 - process_forecast.py - Line: 97 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-09
2025-01-16 14:37:38,552 - process_forecast.py - Line: 113 - INFO - Data successfully written to output/forecast_2024-10-07.csv
2025-01-16 14:37:38,552 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 14:37:38,552 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 14:38:30,863 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:38:30,870 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:38:30,873 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 14:38:30,879 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 14:38:30,880 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:38:30,880 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:38:30,880 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 14:38:30,884 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 14:38:30,885 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:38:30,886 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:38:30,886 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:38:30,886 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:38:30,886 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:38:30,893 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-16 14:38:30,893 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 14:38:30,893 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:38:30,894 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:38:30,894 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:38:30,894 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:38:30,895 - process_current.py - Line: 85 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:38:30,895 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:38:30,895 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:38:30,896 - process_current.py - Line: 85 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:38:30,896 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:38:30,918 - process_current.py - Line: 104 - INFO - Data successfully written to output/raw/current_2024-10-07.csv
2025-01-16 14:38:30,919 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-07
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-08
2025-01-16 14:38:30,919 - etl_helpers.py - Line: 113 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-09
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-07
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-08
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-09
2025-01-16 14:38:30,919 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-07
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-08
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-09
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-07
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-08
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-09
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-07
2025-01-16 14:38:30,923 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-08
2025-01-16 14:38:30,925 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-09
2025-01-16 14:38:30,943 - process_forecast.py - Line: 114 - INFO - Data successfully written to output/raw/forecast_2024-10-07.csv
2025-01-16 14:38:30,943 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 14:38:30,943 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 14:53:17,370 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:53:17,377 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:53:17,382 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 14:53:17,387 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 14:53:17,389 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 14:53:17,393 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:53:17,394 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:53:17,394 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 14:53:17,396 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 14:53:17,396 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:53:17,403 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:53:17,403 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:53:17,403 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:53:17,403 - process_location.py - Line: 87 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:53:17,416 - process_location.py - Line: 103 - INFO - Data successfully written to output/raw/location_2024-10-07.csv !
2025-01-16 14:53:17,416 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 14:53:17,417 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 14:53:17,417 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 14:53:17,417 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 14:53:17,418 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:53:17,418 - process_current.py - Line: 85 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:53:17,418 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 14:53:17,418 - validation_helpers.py - Line: 210 - WARNING - Timestamp inconsistency detected! Difference exceeds 15 minutes.
2025-01-16 14:53:17,418 - process_current.py - Line: 85 - WARNING - Timestamp inconsistency detected!! Please review the data source.
2025-01-16 14:53:17,418 - process_current.py - Line: 88 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 14:53:17,424 - process_current.py - Line: 104 - INFO - Data successfully written to output/raw/current_2024-10-07.csv
2025-01-16 14:53:17,424 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 14:53:17,424 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-07
2025-01-16 14:53:17,426 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-08
2025-01-16 14:53:17,426 - etl_helpers.py - Line: 113 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 14:53:17,427 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-10-09
2025-01-16 14:53:17,427 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-07
2025-01-16 14:53:17,427 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-08
2025-01-16 14:53:17,428 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-10-09
2025-01-16 14:53:17,428 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-07
2025-01-16 14:53:17,428 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-08
2025-01-16 14:53:17,428 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-10-09
2025-01-16 14:53:17,429 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-07
2025-01-16 14:53:17,429 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-08
2025-01-16 14:53:17,429 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-10-09
2025-01-16 14:53:17,429 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-07
2025-01-16 14:53:17,430 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-08
2025-01-16 14:53:17,431 - process_forecast.py - Line: 98 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-10-09
2025-01-16 14:53:17,434 - process_forecast.py - Line: 114 - INFO - Data successfully written to output/raw/forecast_2024-10-07.csv
2025-01-16 14:53:17,434 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 14:53:17,434 - main_etl_runner.py - Line: 65 - INFO - Comparing current vs forecast temperatures...
2025-01-16 14:53:17,434 - compare_temperatures.py - Line: 53 - INFO - -- Starting temperature comparison process
2025-01-16 14:53:17,434 - compare_temperatures.py - Line: 37 - INFO - -- Loading data from CSV files
2025-01-16 14:53:17,434 - etl_helpers.py - Line: 166 - INFO - Searching for the latest CSV file for current in output
2025-01-16 14:53:17,434 - etl_helpers.py - Line: 190 - ERROR - File not found error: No CSV files found for current in output
2025-01-16 14:53:17,434 - compare_temperatures.py - Line: 45 - ERROR - !! Error loading CSV files: No CSV files found for current in output
2025-01-16 14:53:17,434 - compare_temperatures.py - Line: 114 - ERROR - !! Error during temperature comparison process: No CSV files found for current in output
2025-01-16 14:53:17,434 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: No CSV files found for current in output
2025-01-16 14:53:17,434 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: No CSV files found for current in output
2025-01-16 14:56:02,170 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 14:56:02,177 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 14:56:02,177 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 14:56:02,182 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 14:56:02,187 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 14:56:02,188 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 14:56:02,188 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 14:56:02,189 - main_etl_runner.py - Line: 65 - INFO - Comparing current vs forecast temperatures...
2025-01-16 14:56:02,189 - compare_temperatures.py - Line: 53 - INFO - -- Starting temperature comparison process
2025-01-16 14:56:02,189 - compare_temperatures.py - Line: 37 - INFO - -- Loading data from CSV files
2025-01-16 14:56:02,189 - etl_helpers.py - Line: 166 - INFO - Searching for the latest CSV file for current in output
2025-01-16 14:56:02,190 - etl_helpers.py - Line: 190 - ERROR - File not found error: No CSV files found for current in output
2025-01-16 14:56:02,190 - compare_temperatures.py - Line: 45 - ERROR - !! Error loading CSV files: No CSV files found for current in output
2025-01-16 14:56:02,190 - compare_temperatures.py - Line: 114 - ERROR - !! Error during temperature comparison process: No CSV files found for current in output
2025-01-16 14:56:02,191 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: No CSV files found for current in output
2025-01-16 14:56:02,191 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: No CSV files found for current in output
2025-01-16 15:06:38,991 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:06:38,998 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:06:39,003 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:06:39,006 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:06:39,010 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:06:39,010 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:06:39,010 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:06:39,013 - main_etl_runner.py - Line: 65 - INFO - Comparing current vs forecast temperatures...
2025-01-16 15:06:39,013 - compare_temperatures.py - Line: 54 - INFO - -- Starting temperature comparison process
2025-01-16 15:06:39,013 - compare_temperatures.py - Line: 38 - INFO - -- Loading data from CSV files
2025-01-16 15:06:39,014 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for current in output/raw
2025-01-16 15:06:39,014 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\current_2024-10-07.csv
2025-01-16 15:06:39,023 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\current_2024-10-07.csv with 5 rows and 10 columns.
2025-01-16 15:06:39,023 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:06:39,023 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:06:39,029 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:06:39,030 - compare_temperatures.py - Line: 41 - INFO - Successfully loaded current and forecast CSV files.
2025-01-16 15:06:39,064 - compare_temperatures.py - Line: 115 - INFO - Temperature comparison completed successfully and saved to output/insights/temperature_comparison_2024-10-07.csv.
2025-01-16 15:06:39,065 - main_etl_runner.py - Line: 67 - INFO - Temperature comparison completed.
2025-01-16 15:06:39,065 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 15:09:17,523 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:09:17,526 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:09:17,528 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:09:17,530 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:09:17,535 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:09:17,535 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:09:17,535 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:09:17,535 - main_etl_runner.py - Line: 70 - INFO - Identifying the highest temperature day per city...
2025-01-16 15:09:17,536 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: 'MainETLRunner' object has no attribute 'highest_temp_identifier'
2025-01-16 15:09:17,536 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: 'MainETLRunner' object has no attribute 'highest_temp_identifier'
2025-01-16 15:09:39,020 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:09:39,025 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:09:39,032 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:09:39,035 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:09:39,040 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:09:39,046 - identify_highest_temperature.py - Line: 28 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 15:09:39,046 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:09:39,046 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:09:39,046 - main_etl_runner.py - Line: 70 - INFO - Identifying the highest temperature day per city...
2025-01-16 15:09:39,048 - identify_highest_temperature.py - Line: 51 - INFO - -- Starting highest temperature identification process
2025-01-16 15:09:39,048 - identify_highest_temperature.py - Line: 38 - INFO - -- Loading forecast data from CSV file
2025-01-16 15:09:39,048 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:09:39,048 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:09:39,056 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:09:39,056 - identify_highest_temperature.py - Line: 40 - INFO - Successfully loaded forecast CSV file.
2025-01-16 15:09:39,089 - identify_highest_temperature.py - Line: 92 - INFO - Highest temperature identification completed successfully and saved to output/insights/highest_temperature_by_city_2024-10-07.csv.
2025-01-16 15:09:39,089 - main_etl_runner.py - Line: 72 - INFO - Highest temperature identification completed.
2025-01-16 15:09:39,089 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 15:14:23,517 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:14:23,521 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:14:23,527 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:14:23,532 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:14:23,537 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:14:23,546 - identify_highest_temperature.py - Line: 28 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 15:14:23,552 - temperature_statistics_by_city.py - Line: 28 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 15:14:23,553 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:14:23,555 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:14:23,555 - main_etl_runner.py - Line: 70 - INFO - Identifying the highest temperature day per city...
2025-01-16 15:14:23,555 - identify_highest_temperature.py - Line: 51 - INFO - -- Starting highest temperature identification process
2025-01-16 15:14:23,556 - identify_highest_temperature.py - Line: 38 - INFO - -- Loading forecast data from CSV file
2025-01-16 15:14:23,556 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:14:23,556 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:14:23,572 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:14:23,574 - identify_highest_temperature.py - Line: 40 - INFO - Successfully loaded forecast CSV file.
2025-01-16 15:14:23,603 - identify_highest_temperature.py - Line: 92 - INFO - Highest temperature identification completed successfully and saved to output/insights/highest_temperature_by_city_2024-10-07.csv.
2025-01-16 15:14:23,605 - main_etl_runner.py - Line: 72 - INFO - Highest temperature identification completed.
2025-01-16 15:14:23,606 - main_etl_runner.py - Line: 75 - INFO - Calculating temperature statistics...
2025-01-16 15:14:23,606 - temperature_statistics_by_city.py - Line: 51 - INFO - -- Starting temperature statistics calculation
2025-01-16 15:14:23,607 - temperature_statistics_by_city.py - Line: 38 - INFO - -- Loading forecast data from CSV file
2025-01-16 15:14:23,607 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:14:23,608 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:14:23,612 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:14:23,612 - temperature_statistics_by_city.py - Line: 40 - INFO - Successfully loaded forecast CSV file.
2025-01-16 15:14:23,670 - temperature_statistics_by_city.py - Line: 109 - INFO - Temperature statistics calculated successfully and saved to output/insights/temperature_statistics_by_city_2024-10-07.csv.
2025-01-16 15:14:23,671 - main_etl_runner.py - Line: 77 - INFO - Temperature statistics calculated successfully.
2025-01-16 15:14:23,672 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 15:24:34,173 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:24:34,174 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:24:34,175 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:24:34,175 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:24:34,176 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:24:34,179 - identify_highest_temperature.py - Line: 28 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 15:24:34,183 - temperature_statistics_by_city.py - Line: 28 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 15:24:34,188 - city_compare_visualizations.py - Line: 29 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 15:24:34,188 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:24:34,189 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:24:34,189 - main_etl_runner.py - Line: 75 - INFO - Calculating temperature statistics...
2025-01-16 15:24:34,189 - temperature_statistics_by_city.py - Line: 51 - INFO - -- Starting temperature statistics calculation
2025-01-16 15:24:34,189 - temperature_statistics_by_city.py - Line: 38 - INFO - -- Loading forecast data from CSV file
2025-01-16 15:24:34,190 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:24:34,190 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:24:34,193 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:24:34,193 - temperature_statistics_by_city.py - Line: 40 - INFO - Successfully loaded forecast CSV file.
2025-01-16 15:24:34,212 - temperature_statistics_by_city.py - Line: 109 - INFO - Temperature statistics calculated successfully and saved to output/insights/temperature_statistics_by_city_2024-10-07.csv.
2025-01-16 15:24:34,214 - main_etl_runner.py - Line: 77 - INFO - Temperature statistics calculated successfully.
2025-01-16 15:24:34,214 - main_etl_runner.py - Line: 80 - INFO - Generating city temperature visualizations...
2025-01-16 15:24:34,214 - city_compare_visualizations.py - Line: 62 - INFO - -- Starting city comparison visualization generation
2025-01-16 15:24:34,214 - city_compare_visualizations.py - Line: 39 - INFO - -- Loading forecast and current data from CSV files
2025-01-16 15:24:34,215 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:24:34,215 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:24:34,217 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:24:34,218 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for current in output/raw
2025-01-16 15:24:34,218 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\current_2024-10-07.csv
2025-01-16 15:24:34,225 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\current_2024-10-07.csv with 5 rows and 10 columns.
2025-01-16 15:24:34,226 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for location in output/raw
2025-01-16 15:24:34,226 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\location_2024-10-07.csv
2025-01-16 15:24:34,233 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\location_2024-10-07.csv with 5 rows and 11 columns.
2025-01-16 15:24:34,238 - city_compare_visualizations.py - Line: 51 - INFO - Successfully loaded CSV files and merged with location data.
2025-01-16 15:24:34,719 - city_compare_visualizations.py - Line: 136 - INFO - City comparison visualization completed successfully and saved to output/insights/city_temperature_comparison_2024-10-07.png
2025-01-16 15:24:34,720 - main_etl_runner.py - Line: 82 - INFO - City comparison visualization completed.
2025-01-16 15:24:34,720 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 15:27:55,055 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 15:27:55,057 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 15:27:55,060 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 15:27:55,064 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 15:27:55,067 - compare_temperatures.py - Line: 28 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 15:27:55,070 - identify_highest_temperature.py - Line: 28 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 15:27:55,076 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 15:27:55,080 - city_compare_visualizations.py - Line: 29 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 15:27:55,081 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 15:27:55,081 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 15:27:55,081 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 15:27:55,081 - main_etl_runner.py - Line: 80 - INFO - Generating city temperature visualizations...
2025-01-16 15:27:55,081 - city_compare_visualizations.py - Line: 62 - INFO - -- Starting city comparison visualization generation
2025-01-16 15:27:55,088 - city_compare_visualizations.py - Line: 39 - INFO - -- Loading forecast and current data from CSV files
2025-01-16 15:27:55,088 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:27:55,088 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:27:55,098 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:27:55,099 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for current in output/raw
2025-01-16 15:27:55,099 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\current_2024-10-07.csv
2025-01-16 15:27:55,102 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\current_2024-10-07.csv with 5 rows and 10 columns.
2025-01-16 15:27:55,102 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for location in output/raw
2025-01-16 15:27:55,102 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\location_2024-10-07.csv
2025-01-16 15:27:55,111 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\location_2024-10-07.csv with 5 rows and 11 columns.
2025-01-16 15:27:55,116 - city_compare_visualizations.py - Line: 51 - INFO - Successfully loaded CSV files and merged with location data.
2025-01-16 15:27:55,483 - city_compare_visualizations.py - Line: 136 - INFO - City comparison visualization completed successfully and saved to output/insights/city_temperature_comparison_2024-10-07.png
2025-01-16 15:27:55,483 - main_etl_runner.py - Line: 82 - INFO - City comparison visualization completed.
2025-01-16 15:27:55,484 - main_etl_runner.py - Line: 85 - INFO - Identifying weather alerts...
2025-01-16 15:27:55,484 - weather_alerts.py - Line: 50 - INFO - -- Starting weather alerts identification process
2025-01-16 15:27:55,485 - weather_alerts.py - Line: 37 - INFO - -- Loading forecast data from CSV file
2025-01-16 15:27:55,485 - etl_helpers.py - Line: 167 - INFO - Searching for the latest CSV file for forecast in output/raw
2025-01-16 15:27:55,485 - etl_helpers.py - Line: 180 - INFO - Loading data from: output/raw\forecast_2024-10-07.csv
2025-01-16 15:27:55,489 - etl_helpers.py - Line: 187 - INFO - Data successfully loaded from output/raw\forecast_2024-10-07.csv with 15 rows and 26 columns.
2025-01-16 15:27:55,490 - weather_alerts.py - Line: 39 - INFO - Successfully loaded forecast CSV file.
2025-01-16 15:27:55,518 - weather_alerts.py - Line: 96 - INFO - Weather alerts identified successfully and saved to output/insights/weather_alerts_summary_2024-10-07.csv.
2025-01-16 15:27:55,519 - main_etl_runner.py - Line: 87 - INFO - Weather alert identification completed.
2025-01-16 15:27:55,520 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:04:27,845 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:04:27,847 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:04:27,848 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:04:27,851 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:04:27,853 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:04:27,856 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:04:27,857 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:04:27,860 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:04:27,863 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:04:27,864 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:04:27,864 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:04:27,864 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:04:27,868 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:04:27,869 - process_location.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:04:27,869 - process_location.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:04:27,869 - process_location.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:04:27,869 - process_location.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:04:27,869 - process_location.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:04:27,882 - process_location.py - Line: 64 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:04:27,882 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:04:27,882 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:18:36,553 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:18:36,555 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:18:36,555 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:18:36,555 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:18:36,556 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:18:36,556 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:18:36,557 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:18:36,557 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:18:36,558 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:18:36,558 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:18:36,558 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:18:36,558 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:18:36,559 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:18:36,560 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:18:36,560 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:18:36,561 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:18:36,562 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:18:36,562 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:18:36,575 - process_location.py - Line: 60 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:18:36,575 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:18:36,575 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:19:29,214 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:19:29,214 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:19:29,214 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:19:29,216 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:19:29,216 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:19:29,216 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:19:29,217 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:19:29,217 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:19:29,217 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:19:29,217 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:19:29,217 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:19:29,217 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:19:29,219 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:19:29,220 - process_location.py - Line: 46 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:19:29,222 - process_location.py - Line: 46 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:19:29,223 - process_location.py - Line: 46 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:19:29,224 - process_location.py - Line: 46 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:19:29,227 - process_location.py - Line: 46 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:19:29,241 - process_location.py - Line: 61 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:19:29,241 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:19:29,241 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:19:44,694 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:19:44,694 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:19:44,694 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:19:44,694 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:19:44,696 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:19:44,697 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:19:44,697 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:19:44,697 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:19:44,697 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:19:44,697 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:19:44,698 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:19:44,698 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:19:44,698 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:19:44,699 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:19:44,699 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:19:44,699 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:19:44,701 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:19:44,701 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:19:44,711 - process_location.py - Line: 61 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:19:44,712 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:19:44,712 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:20:03,670 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:20:03,671 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:20:03,671 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:20:03,671 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:20:03,672 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:20:03,672 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:20:03,672 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:20:03,673 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:20:03,674 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:20:03,674 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:20:03,674 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:20:03,674 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:20:03,675 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:20:03,676 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:20:03,676 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:20:03,677 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:20:03,677 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:20:03,678 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:20:03,688 - process_location.py - Line: 61 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:20:03,688 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:20:03,688 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:32:25,426 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:32:25,427 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:32:25,427 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:32:25,427 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:32:25,427 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:32:25,428 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:32:25,428 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:32:25,428 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:32:25,429 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:32:25,429 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:32:25,429 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:32:25,429 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:32:25,429 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:32:25,431 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:25,431 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:25,432 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:25,432 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:25,432 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:25,443 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:32:25,443 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:32:25,444 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:25,444 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:25,444 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:25,445 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:25,445 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:25,445 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:25,446 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:25,446 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:25,446 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:25,446 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:25,447 - process_current.py - Line: 66 - ERROR - !! Error writing data to CSV: 'localtime'
2025-01-16 21:32:25,447 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: 'localtime'
2025-01-16 21:32:25,447 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: 'localtime'
2025-01-16 21:32:50,478 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:32:50,499 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:32:50,500 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:32:50,500 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:32:50,501 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:32:50,501 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:32:50,502 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:32:50,502 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:32:50,502 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:32:50,502 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:32:50,502 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:32:50,503 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:32:50,503 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:32:50,504 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:50,504 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:50,504 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:50,505 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:50,505 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:50,528 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:32:50,529 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:32:50,530 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:50,530 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:32:50,530 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:50,530 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 46 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:50,531 - process_current.py - Line: 49 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:32:50,536 - process_current.py - Line: 63 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:32:50,536 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:32:50,536 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:35:30,928 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:35:30,928 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:35:30,928 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:35:30,929 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:35:30,929 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:35:30,929 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:35:30,931 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:35:30,931 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:35:30,931 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:35:30,931 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:35:30,931 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:35:30,931 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:35:30,932 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:35:30,933 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:35:30,933 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:35:30,933 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:35:30,933 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:35:30,934 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:35:30,944 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:35:30,944 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:35:30,944 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:35:30,945 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:35:30,945 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:35:30,945 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:35:30,946 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:35:30,946 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:35:30,946 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:35:30,946 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:35:30,946 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:35:30,947 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:35:30,951 - process_current.py - Line: 62 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:35:30,953 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:35:30,953 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:44:56,097 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:44:56,098 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:44:56,098 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:44:56,099 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:44:56,099 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:44:56,100 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:44:56,100 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:44:56,100 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:44:56,100 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:44:56,100 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:44:56,100 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:44:56,101 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:44:56,101 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:44:56,101 - process_location.py - Line: 48 - ERROR - !! Error processing data for city: Bangkok, Thailand, Error: transform_helper() missing 1 required positional argument: 'forecast_day'
2025-01-16 21:44:56,101 - process_location.py - Line: 48 - ERROR - !! Error processing data for city: Chiang Mai, Thailand, Error: transform_helper() missing 1 required positional argument: 'forecast_day'
2025-01-16 21:44:56,101 - process_location.py - Line: 48 - ERROR - !! Error processing data for city: Phuket, Thailand, Error: transform_helper() missing 1 required positional argument: 'forecast_day'
2025-01-16 21:44:56,102 - process_location.py - Line: 48 - ERROR - !! Error processing data for city: Pattaya, Thailand, Error: transform_helper() missing 1 required positional argument: 'forecast_day'
2025-01-16 21:44:56,102 - process_location.py - Line: 48 - ERROR - !! Error processing data for city: Hat Yai, Thailand, Error: transform_helper() missing 1 required positional argument: 'forecast_day'
2025-01-16 21:44:56,102 - process_location.py - Line: 62 - ERROR - !! Error writing data to CSV: list index out of range
2025-01-16 21:44:56,102 - main_etl_runner.py - Line: 92 - ERROR - Critical error during ETL pipeline execution: list index out of range
2025-01-16 21:44:56,102 - main_etl_runner.py - Line: 105 - ERROR - Critical error during ETL execution: list index out of range
2025-01-16 21:45:52,746 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:45:52,747 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:45:52,747 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:45:52,748 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:45:52,748 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:45:52,748 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:45:52,749 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:45:52,750 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:45:52,750 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:45:52,751 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:45:52,751 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:45:52,751 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:45:52,751 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:45:52,752 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:45:52,752 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:45:52,752 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:45:52,753 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:45:52,753 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:45:52,763 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:45:52,764 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:45:52,765 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:45:52,765 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:45:52,766 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:45:52,766 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:45:52,766 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:45:52,766 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:45:52,767 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:45:52,767 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:45:52,767 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:45:52,768 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:45:52,773 - process_current.py - Line: 62 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:45:52,773 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 21:45:52,773 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-27
2025-01-16 21:45:52,773 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-28
2025-01-16 21:45:52,773 - etl_helpers.py - Line: 118 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 21:45:52,773 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-29
2025-01-16 21:45:52,775 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-27
2025-01-16 21:45:52,775 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-28
2025-01-16 21:45:52,775 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-29
2025-01-16 21:45:52,776 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-27
2025-01-16 21:45:52,776 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-28
2025-01-16 21:45:52,777 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-29
2025-01-16 21:45:52,777 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-27
2025-01-16 21:45:52,778 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-28
2025-01-16 21:45:52,778 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-29
2025-01-16 21:45:52,778 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-27
2025-01-16 21:45:52,778 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-28
2025-01-16 21:45:52,778 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-29
2025-01-16 21:45:52,782 - process_forecast.py - Line: 64 - INFO - Data successfully written to output/raw/forecast_2024-05-27.csv
2025-01-16 21:45:52,783 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:45:52,783 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:47:31,330 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:47:31,331 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:47:31,331 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:47:31,332 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:47:31,332 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:47:31,332 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:47:31,333 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:47:31,333 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:47:31,333 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:47:31,334 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:47:31,334 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:47:31,334 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:47:31,335 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:47:31,336 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:47:31,336 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:47:31,336 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:47:31,336 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:47:31,337 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:47:31,345 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:47:31,346 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:47:31,346 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:47:31,346 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:47:31,347 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:47:31,347 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:47:31,347 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:47:31,347 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:47:31,347 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:47:31,348 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:47:31,348 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:47:31,348 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:47:31,353 - process_current.py - Line: 62 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:47:31,353 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 21:47:31,353 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-27
2025-01-16 21:47:31,353 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-28
2025-01-16 21:47:31,355 - etl_helpers.py - Line: 118 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-29
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-27
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-28
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-29
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-27
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-28
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-29
2025-01-16 21:47:31,355 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-27
2025-01-16 21:47:31,356 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-28
2025-01-16 21:47:31,357 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-29
2025-01-16 21:47:31,357 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-27
2025-01-16 21:47:31,357 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-28
2025-01-16 21:47:31,358 - process_forecast.py - Line: 49 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-29
2025-01-16 21:47:31,365 - process_forecast.py - Line: 64 - INFO - Data successfully written to output/raw/forecast_2024-05-27.csv
2025-01-16 21:47:31,366 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:47:31,366 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:48:34,974 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:48:34,975 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:48:34,976 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:48:34,977 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:48:34,977 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:48:34,977 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:48:34,978 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:48:34,978 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:48:34,978 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:48:34,978 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:48:34,979 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:48:34,979 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:48:34,979 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:48:34,979 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:48:34,980 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:48:34,980 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:48:34,980 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:48:34,981 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:48:34,992 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:48:34,993 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:48:34,993 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:48:34,993 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:48:34,994 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:48:34,994 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:48:34,994 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:48:34,994 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:48:34,995 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:48:34,995 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:48:34,995 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:48:34,995 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:48:35,001 - process_current.py - Line: 62 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:48:35,001 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 21:48:35,002 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-27
2025-01-16 21:48:35,002 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-28
2025-01-16 21:48:35,003 - etl_helpers.py - Line: 118 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 21:48:35,003 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-29
2025-01-16 21:48:35,004 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-27
2025-01-16 21:48:35,005 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-28
2025-01-16 21:48:35,005 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-29
2025-01-16 21:48:35,006 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-27
2025-01-16 21:48:35,007 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-28
2025-01-16 21:48:35,007 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-29
2025-01-16 21:48:35,007 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-27
2025-01-16 21:48:35,008 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-28
2025-01-16 21:48:35,008 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-29
2025-01-16 21:48:35,008 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-27
2025-01-16 21:48:35,009 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-28
2025-01-16 21:48:35,010 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-29
2025-01-16 21:48:35,019 - process_forecast.py - Line: 65 - INFO - Data successfully written to output/raw/forecast_2024-05-27.csv
2025-01-16 21:48:35,020 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:48:35,020 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
2025-01-16 21:49:31,615 - main_etl_runner.py - Line: 101 - INFO - Launching the ETL pipeline...
2025-01-16 21:49:31,616 - process_location.py - Line: 25 - INFO - Configuration for location table loaded successfully
2025-01-16 21:49:31,616 - process_current.py - Line: 25 - INFO - Configuration for current table loaded successfully
2025-01-16 21:49:31,616 - process_forecast.py - Line: 25 - INFO - Configuration for forecast table loaded successfully
2025-01-16 21:49:31,617 - compare_temperatures.py - Line: 27 - INFO - -- Initialized CompareTemperatures class successfully.
2025-01-16 21:49:31,617 - identify_highest_temperature.py - Line: 27 - INFO - -- Initialized IdentifyHighestTemperature class successfully.
2025-01-16 21:49:31,617 - temperature_statistics_by_city.py - Line: 27 - INFO - -- Initialized TemperatureStatistics class successfully.
2025-01-16 21:49:31,618 - city_compare_visualizations.py - Line: 28 - INFO - -- Initialized CityComparisonVisualization class successfully.
2025-01-16 21:49:31,619 - weather_alerts.py - Line: 27 - INFO - -- Initialized WeatherAlerts class successfully.
2025-01-16 21:49:31,619 - main_etl_runner.py - Line: 38 - INFO - ETL Runner initialized successfully.
2025-01-16 21:49:31,619 - main_etl_runner.py - Line: 53 - INFO - -- STARTING THE ETL PIPELINE --
2025-01-16 21:49:31,619 - main_etl_runner.py - Line: 57 - INFO - Flattening and storing data...
2025-01-16 21:49:31,620 - process_location.py - Line: 32 - INFO - - Starting the data processing for location table...
2025-01-16 21:49:31,621 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:49:31,621 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:49:31,621 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:49:31,621 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:49:31,621 - process_location.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:49:31,631 - process_location.py - Line: 59 - INFO - Data successfully written to output/raw/location_2024-05-27.csv !
2025-01-16 21:49:31,631 - process_current.py - Line: 32 - INFO - - Starting the data processing for current table...
2025-01-16 21:49:31,631 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:49:31,631 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Bangkok, Thailand
2025-01-16 21:49:31,632 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:49:31,632 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Chiang Mai, Thailand
2025-01-16 21:49:31,632 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:49:31,632 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Phuket, Thailand
2025-01-16 21:49:31,632 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:49:31,634 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Pattaya, Thailand
2025-01-16 21:49:31,634 - process_current.py - Line: 45 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:49:31,634 - process_current.py - Line: 48 - INFO - Successfully processed data for city: Hat Yai, Thailand
2025-01-16 21:49:31,640 - process_current.py - Line: 62 - INFO - Data successfully written to output/raw/current_2024-05-27.csv !
2025-01-16 21:49:31,640 - process_forecast.py - Line: 32 - INFO - - Starting the data processing for forecast table...
2025-01-16 21:49:31,641 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-27
2025-01-16 21:49:31,642 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-28
2025-01-16 21:49:31,642 - etl_helpers.py - Line: 118 - ERROR - Data type conversion error for value 'invalid_data' to FLOAT: could not convert string to float: 'invalid_data'
2025-01-16 21:49:31,642 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Bangkok, Thailand on 2024-05-29
2025-01-16 21:49:31,642 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-27
2025-01-16 21:49:31,643 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-28
2025-01-16 21:49:31,643 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Chiang Mai, Thailand on 2024-05-29
2025-01-16 21:49:31,644 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-27
2025-01-16 21:49:31,644 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-28
2025-01-16 21:49:31,644 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Phuket, Thailand on 2024-05-29
2025-01-16 21:49:31,646 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-27
2025-01-16 21:49:31,646 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-28
2025-01-16 21:49:31,647 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Pattaya, Thailand on 2024-05-29
2025-01-16 21:49:31,647 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-27
2025-01-16 21:49:31,647 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-28
2025-01-16 21:49:31,649 - process_forecast.py - Line: 50 - INFO - Successfully processed forecast data for city: Hat Yai, Thailand on 2024-05-29
2025-01-16 21:49:31,655 - process_forecast.py - Line: 65 - INFO - Data successfully written to output/raw/forecast_2024-05-27.csv
2025-01-16 21:49:31,656 - main_etl_runner.py - Line: 62 - INFO - Flattening process completed successfully.
2025-01-16 21:49:31,656 - main_etl_runner.py - Line: 89 - INFO - -- ETL PIPELINE COMPLETED SUCCESSFULLY --
